import argparse
import json
import math
import sys
from pathlib import Path
from typing import Any

import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts.analysis.odo_nhc_update_sweep import ensure_dir, load_yaml, rel_from_root  # noqa: E402
from scripts.analysis.run_mounting_yaw_nhc_bgz_compare import BASE_SHORT_CONFIG, mtime_text  # noqa: E402


MECHANISM_DEFAULT = Path(
    "output/debug_mounting_yaw_first_update_geometry_r1_20260323/"
    "cases/baseline/SOL_baseline_mechanism.csv"
)
OUTPUT_DIR_DEFAULT = Path("output/debug_mounting_yaw_first_nhc_predict_origin_r1_20260323")


def parse_vec(text: str) -> list[float]:
    stripped = str(text).strip()
    if stripped == "[]" or not stripped:
        return []
    if stripped[0] == "[" and stripped[-1] == "]":
        stripped = stripped[1:-1]
    if not stripped:
        return []
    return [float(part) for part in stripped.split(";") if part]


def vec_norm(values: list[float]) -> float:
    return math.sqrt(sum(v * v for v in values))


def read_code_markers(path: Path, markers: list[str]) -> dict[str, bool]:
    text = path.read_text(encoding="utf-8")
    return {marker: (marker in text) for marker in markers}


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Audit whether the first NHC pre-update bg_z-att_z route is generated by predict."
    )
    parser.add_argument("--config", type=Path, default=BASE_SHORT_CONFIG)
    parser.add_argument("--mechanism", type=Path, default=MECHANISM_DEFAULT)
    parser.add_argument("--output-dir", type=Path, default=OUTPUT_DIR_DEFAULT)
    args = parser.parse_args()

    config_path = REPO_ROOT / args.config
    mechanism_path = REPO_ROOT / args.mechanism
    outdir = REPO_ROOT / args.output_dir
    ensure_dir(outdir)

    cfg = load_yaml(config_path)
    mechanism_df = pd.read_csv(mechanism_path)
    mechanism_df.insert(0, "seq_idx", range(1, len(mechanism_df) + 1))
    first_row = mechanism_df.iloc[0]

    init_cfg = cfg["fusion"]["init"]
    constraints = cfg["fusion"]["constraints"]

    init_code = REPO_ROOT / "src/app/initialization.cpp"
    pipeline_code = REPO_ROOT / "src/app/pipeline_fusion.cpp"
    init_markers = read_code_markers(
        init_code,
        [
            "P0 = Matrix<double, kStateDim, kStateDim>::Zero();",
            "P0(i, i) = options.init.P0_diag(i);",
        ],
    )
    pipeline_markers = read_code_markers(
        pipeline_code,
        [
            "engine.AddImu(dataset.imu[0]);",
            "for (size_t i = 1; i < dataset.imu.size(); ++i)",
            "if (!engine.Predict()) continue;",
            "RunNhcUpdate(engine, dataset.imu[i], options.constraints, mounting_base_rpy,",
            "last_odo_speed = RunOdoUpdate(engine, dataset, options.constraints,",
            "gnss_updated = RunGnssUpdate(engine, dataset, gnss_idx, t, options, diag,",
        ],
    )

    p_row_bg_z_att = parse_vec(first_row["p_row_bg_z_att_vec"])
    p_row_bg_z_bg = parse_vec(first_row["p_row_bg_z_bg_vec"])
    h_att_z = parse_vec(first_row["h_att_z_vec"])
    h_bg_z = parse_vec(first_row["h_bg_z_vec"])
    num_bg_z_total = parse_vec(first_row["num_bg_z_vec"])
    num_bg_z_from_att_z = parse_vec(first_row["num_bg_z_from_att_z_vec"])
    num_bg_z_from_bg_z = parse_vec(first_row["num_bg_z_from_bg_z_vec"])

    p_bgz_attz = p_row_bg_z_att[2] if len(p_row_bg_z_att) >= 3 else float("nan")
    p_bgz_bgz = p_row_bg_z_bg[2] if len(p_row_bg_z_bg) >= 3 else float("nan")
    reconstructed_bg = [p_bgz_bgz * v for v in h_bg_z]
    reconstructed_att = [p_bgz_attz * v for v in h_att_z]

    report: dict[str, Any] = {
        "config_path": rel_from_root(config_path, REPO_ROOT),
        "mechanism_path": rel_from_root(mechanism_path, REPO_ROOT),
        "config_mtime": mtime_text(config_path),
        "mechanism_mtime": mtime_text(mechanism_path),
        "short_window_mounting_base_yaw_deg": float(constraints["imu_mounting_angle"][2]),
        "short_window_mounting_yaw0_deg": float(init_cfg["mounting_yaw0"]),
        "custom_p0_diag_enabled": bool(init_cfg.get("P0_diag")),
        "initial_p0_bgz_var": float(init_cfg["P0_diag"][14]),
        "initial_p0_attz_var": float(init_cfg["P0_diag"][8]),
        "initial_p0_bgz_attz_cov": 0.0,
        "first_mechanism_seq": int(first_row["seq_idx"]),
        "first_mechanism_tag": str(first_row["tag"]),
        "first_mechanism_t_meas": float(first_row["t_meas"]),
        "first_num_bg_z_vec": num_bg_z_total,
        "first_p_row_bg_z_att_vec": p_row_bg_z_att,
        "first_p_row_bg_z_bg_vec": p_row_bg_z_bg,
        "first_h_att_z_vec": h_att_z,
        "first_h_bg_z_vec": h_bg_z,
        "first_num_bg_z_from_att_z_vec": num_bg_z_from_att_z,
        "first_num_bg_z_from_bg_z_vec": num_bg_z_from_bg_z,
        "reconstructed_num_bg_z_from_att_z_vec": reconstructed_att,
        "reconstructed_num_bg_z_from_bg_z_vec": reconstructed_bg,
        "num_bg_z_total_norm": vec_norm(num_bg_z_total),
        "num_bg_z_from_bg_z_norm": vec_norm(num_bg_z_from_bg_z),
        "num_bg_z_from_att_z_norm": vec_norm(num_bg_z_from_att_z),
        "num_bg_z_from_bg_z_ratio": vec_norm(num_bg_z_from_bg_z) / vec_norm(num_bg_z_total),
        "num_bg_z_from_att_z_ratio": vec_norm(num_bg_z_from_att_z) / vec_norm(num_bg_z_total),
        "init_code_markers": init_markers,
        "pipeline_code_markers": pipeline_markers,
        "zupt_enabled": bool(constraints["enable_zupt"]),
        "uwb_path": str(cfg["fusion"]["uwb_path"]),
    }

    logic_checks = {
        "p0_is_diagonal_by_code": all(init_markers.values()),
        "first_update_row_is_nhc": report["first_mechanism_seq"] == 1
        and report["first_mechanism_tag"] == "NHC",
        "predict_happens_before_nhc_by_code": all(
            pipeline_markers[key]
            for key in [
                "engine.AddImu(dataset.imu[0]);",
                "for (size_t i = 1; i < dataset.imu.size(); ++i)",
                "if (!engine.Predict()) continue;",
                "RunNhcUpdate(engine, dataset.imu[i], options.constraints, mounting_base_rpy,",
            ]
        ),
        "no_zupt_in_case": not report["zupt_enabled"],
        "no_uwb_in_case": report["uwb_path"] == "",
    }
    report["logic_checks"] = logic_checks
    report["predict_origin_supported"] = all(logic_checks.values())

    summary_lines = [
        "# First NHC Predict-Origin Audit",
        "",
        "目标：验证 baseline short-window 中首个关键 `NHC` 前的 `P(bg_z,att_z)` 是否在没有任何先验量测更新的情况下，由初始化对角 `P0` 经首个预测步生成。",
        "",
        "## Inputs",
        "",
        f"- config: `{report['config_path']}`",
        f"- mechanism: `{report['mechanism_path']}`",
        f"- config_mtime: `{report['config_mtime']}`",
        f"- mechanism_mtime: `{report['mechanism_mtime']}`",
        "",
        "## Config / Code Checks",
        "",
        f"- `mounting base yaw = {report['short_window_mounting_base_yaw_deg']:.2f} deg`, `mounting_yaw0 = {report['short_window_mounting_yaw0_deg']:.2f} deg`.",
        f"- `P0_diag[att_z] = {report['initial_p0_attz_var']:.12g}`, `P0_diag[bg_z] = {report['initial_p0_bgz_var']:.12g}`, initial `P(bg_z,att_z)=0` by diagonal initialization code path.",
        f"- first mechanism row: `seq={report['first_mechanism_seq']}`, `tag={report['first_mechanism_tag']}`, `t={report['first_mechanism_t_meas']:.6f}`.",
        f"- code checks: `p0_is_diagonal_by_code={logic_checks['p0_is_diagonal_by_code']}`, `predict_happens_before_nhc_by_code={logic_checks['predict_happens_before_nhc_by_code']}`, `no_zupt_in_case={logic_checks['no_zupt_in_case']}`, `no_uwb_in_case={logic_checks['no_uwb_in_case']}`.",
        "",
        "## First-Row Decomposition",
        "",
        f"- `p_row_bg_z_bg=[{'; '.join(f'{v:.12g}' for v in p_row_bg_z_bg)}]` and only `bg_z` is nonzero.",
        f"- `p_row_bg_z_att=[{'; '.join(f'{v:.12g}' for v in p_row_bg_z_att)}]` and only `att_z` is material.",
        f"- `num_bg_z_from_bg_z_vec=[{'; '.join(f'{v:.12g}' for v in num_bg_z_from_bg_z)}]` (`{report['num_bg_z_from_bg_z_ratio']:.6f}` of total norm).",
        f"- `num_bg_z_from_att_z_vec=[{'; '.join(f'{v:.12g}' for v in num_bg_z_from_att_z)}]` (`{report['num_bg_z_from_att_z_ratio']:.6f}` of total norm).",
        f"- reconstructed direct term `P(bg_z,bg_z) * H_bg_z = [{'; '.join(f'{v:.12g}' for v in reconstructed_bg)}]`.",
        f"- reconstructed propagated term `P(bg_z,att_z) * H_att_z = [{'; '.join(f'{v:.12g}' for v in reconstructed_att)}]`.",
        "",
        "## Conclusion",
        "",
    ]
    if report["predict_origin_supported"]:
        summary_lines.append(
            "- 支持当前判断：在本 short-window baseline 中，首个关键 `NHC` 前的 `P(bg_z,att_z)` 不需要任何先验量测更新即可出现；它从初始化对角 `P0` 出发，在首个 predict 后就已存在。"
        )
    else:
        summary_lines.append(
            "- 当前证据不足以单独证明 predict-origin；需要继续补 explicit pre-NHC snapshot."
        )
    summary_lines.append(
        "- baseline 首个坏 route 已可近似写成 `num_bg_z ≈ P(bg_z,bg_z) * H_bg_z + P(bg_z,att_z) * H_att_z`，其中主项是 `bg_z` 自身直达。"
    )
    summary_text = "\n".join(summary_lines) + "\n"

    (outdir / "summary.md").write_text(summary_text, encoding="utf-8")
    (outdir / "report.json").write_text(
        json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8"
    )

    print(f"[done] summary: {outdir / 'summary.md'}")
    print(f"[done] report: {outdir / 'report.json'}")


if __name__ == "__main__":
    main()
